import { NextRequest, NextResponse } from 'next/server';
import { requireAdmin } from '@/lib/admin-auth';
import { query } from '@/lib/db';
import { logAction } from '@/lib/audit';
import { createSupplierUser, supplierEmailExists } from '@/lib/supplier-auth';
import { supplierUserCreateSchema } from '@/lib/validation';
import { getClientIp } from '@/lib/rate-limit';
import { securityLogger } from '@/lib/security-logger';

// GET /api/admin/suppliers - List all supplier users
export async function GET(request: NextRequest) {
  const auth = await requireAdmin('admins.view'); // Using admins permission for now
  if (auth.error) return auth.error;

  try {
    const suppliers = await query<{
      id: string;
      email: string;
      name: string;
      company_name: string;
      phone: string | null;
      supplier_number: string | null;
      is_active: boolean;
      tax_exempt: boolean;
      address_street: string | null;
      address_city: string | null;
      address_state: string | null;
      address_zip: string | null;
      created_at: string;
      updated_at: string;
    }>(
      `SELECT id, email, name, company_name, phone, supplier_number, is_active, tax_exempt, address_street, address_city, address_state, address_zip, created_at, updated_at
       FROM supplier_users
       ORDER BY company_name, name`
    );

    return NextResponse.json(suppliers);
  } catch (error) {
    securityLogger.logError('Failed to fetch supplier users', error, getClientIp(request));
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

// POST /api/admin/suppliers - Create a new supplier user
export async function POST(request: NextRequest) {
  const auth = await requireAdmin('admins.create'); // Using admins permission for now
  if (auth.error) return auth.error;

  const ip = getClientIp(request);

  try {
    const body = await request.json();
    
    // Validate input
    const validationResult = supplierUserCreateSchema.safeParse(body);
    if (!validationResult.success) {
      return NextResponse.json(
        { error: 'Validation failed', details: validationResult.error.issues },
        { status: 400 }
      );
    }

    const { email, name, company_name, password, phone, tax_exempt, address_street, address_city, address_state, address_zip } = validationResult.data;

    // Check if email already exists
    if (await supplierEmailExists(email)) {
      return NextResponse.json(
        { error: 'A supplier with this email already exists' },
        { status: 400 }
      );
    }

    // Create supplier user (supplier_number is auto-generated by database trigger)
    const supplier = await createSupplierUser(
      email, 
      name, 
      company_name, 
      password, 
      phone || undefined, 
      tax_exempt || false,
      address_street,
      address_city,
      address_state,
      address_zip
    );

    await logAction({
      adminUserId: auth.session.adminUser.id,
      action: 'create',
      resourceType: 'admin_user', // Using admin_user as closest match
      resourceId: supplier.id,
      after: {
        email: supplier.email,
        name: supplier.name,
        company_name: supplier.company_name,
        phone: supplier.phone,
        is_active: supplier.is_active,
        type: 'supplier_user',
      } as unknown as Record<string, unknown>,
    });

    securityLogger.logEvent({
      type: 'admin_action',
      ip,
      path: '/api/admin/suppliers',
      method: 'POST',
      details: {
        action: 'supplier_user_created',
        supplier_id: supplier.id,
        supplier_email: supplier.email,
        company_name: supplier.company_name,
      },
      severity: 'low',
    });

    return NextResponse.json(supplier, { status: 201 });
  } catch (error) {
    securityLogger.logError('Failed to create supplier user', error, ip);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

