import { NextRequest, NextResponse } from 'next/server';
import { requireAdmin } from '@/lib/admin-auth';
import { Resend } from 'resend';

/**
 * Test endpoint to verify PDFShift → Resend email flow
 * Tests: PDFShift API → PDF generation → Resend email with PDF attachment
 */
export async function POST(request: NextRequest) {
  try {
    // Check admin auth
    const auth = await requireAdmin();
    if (auth.error) {
      return auth.error;
    }

    if (!process.env.RESEND_API_KEY) {
      return NextResponse.json({ error: 'RESEND_API_KEY not configured' }, { status: 500 });
    }
    const resend = new Resend(process.env.RESEND_API_KEY);
    const FROM_EMAIL = process.env.EMAIL_FROM || 'noreply@example.com';

    const body = await request.json();
    const testEmail = body.email || auth.session?.user?.email;

    if (!testEmail) {
      return NextResponse.json(
        { error: 'Email address required. Provide "email" in request body.' },
        { status: 400 }
      );
    }

    const PDFSHIFT_API_KEY = process.env.PDFSHIFT_API_KEY;
    if (!PDFSHIFT_API_KEY) {
      return NextResponse.json(
        { error: 'PDFSHIFT_API_KEY not configured' },
        { status: 500 }
      );
    }

    // Step 1: Generate PDF using PDFShift
    console.log('🧪 TEST: Generating PDF with PDFShift...');
    const testHTML = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Test PDF</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 20px; }
          h1 { color: #059669; }
        </style>
      </head>
      <body>
        <h1>Test PDF Document</h1>
        <p>This is a test PDF generated by PDFShift and sent via Resend.</p>
        <p>Generated at: ${new Date().toISOString()}</p>
      </body>
      </html>
    `;

    const pdfResponse = await fetch('https://api.pdfshift.io/v3/convert/pdf', {
      method: 'POST',
      headers: {
        'X-API-Key': PDFSHIFT_API_KEY,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        source: testHTML,
        landscape: false,
        use_print: false,
        format: 'Letter',
        margin: {
          top: '48',
          right: '48',
          bottom: '48',
          left: '48',
        },
        disable_backgrounds: false,
        sandbox: false,
        encode: false,
      }),
    });

    if (!pdfResponse.ok) {
      const errorText = await pdfResponse.text();
      return NextResponse.json(
        {
          success: false,
          error: 'PDFShift API error',
          details: {
            status: pdfResponse.status,
            statusText: pdfResponse.statusText,
            error: errorText,
          },
        },
        { status: 500 }
      );
    }

    // Step 2: Validate PDF
    const arrayBuffer = await pdfResponse.arrayBuffer();
    const pdfBuffer = Buffer.from(arrayBuffer);
    const pdfHeader = pdfBuffer.toString('ascii', 0, 4);

    if (pdfHeader !== '%PDF') {
      return NextResponse.json(
        {
          success: false,
          error: 'PDFShift returned invalid PDF',
          details: {
            header: pdfHeader,
            size: pdfBuffer.length,
            contentType: pdfResponse.headers.get('content-type'),
          },
        },
        { status: 500 }
      );
    }

    console.log('🧪 TEST: PDF generated successfully. Size:', pdfBuffer.length, 'bytes');

    // Step 3: Send email with PDF attachment via Resend
    console.log('🧪 TEST: Sending email via Resend with PDF attachment...');
    const emailResult = await resend.emails.send({
      from: FROM_EMAIL,
      to: testEmail,
      subject: 'Test: PDF Attachment from PDFShift + Resend',
      html: `
        <h2>PDF Attachment Test</h2>
        <p>This email contains a PDF attachment generated by PDFShift and sent via Resend.</p>
        <p><strong>PDF Details:</strong></p>
        <ul>
          <li>Size: ${pdfBuffer.length} bytes</li>
          <li>Format: PDF (validated)</li>
          <li>Generated: ${new Date().toISOString()}</li>
        </ul>
        <p>If you can open the attached PDF file, the integration is working correctly!</p>
      `,
      attachments: [
        {
          filename: 'test-pdf-attachment.pdf',
          content: pdfBuffer.toString('base64'),
        },
      ],
    });

    if (emailResult.error) {
      return NextResponse.json(
        {
          success: false,
          error: 'Resend email error',
          details: emailResult.error,
        },
        { status: 500 }
      );
    }

    console.log('🧪 TEST: Email sent successfully! Message ID:', emailResult.data?.id);

    return NextResponse.json({
      success: true,
      message: 'Test email sent successfully with PDF attachment',
      details: {
        pdfShift: {
          status: pdfResponse.status,
          pdfSize: pdfBuffer.length,
          pdfValid: true,
        },
        resend: {
          messageId: emailResult.data?.id,
          to: testEmail,
          from: FROM_EMAIL,
        },
        attachment: {
          filename: 'test-pdf-attachment.pdf',
          size: pdfBuffer.length,
          type: 'application/pdf',
        },
      },
    });
  } catch (error) {
    console.error('🧪 TEST: Error in test endpoint:', error);
    return NextResponse.json(
      {
        success: false,
        error: 'Test failed',
        details: {
          message: error instanceof Error ? error.message : String(error),
          stack: error instanceof Error ? error.stack : undefined,
        },
      },
      { status: 500 }
    );
  }
}

