/**
 * Inventory Transaction Logging Library
 * 
 * Provides functions to log all inventory movements to the inventory_transactions table.
 * Similar to SAP MB51 Material Document List functionality.
 * 
 * Transaction Types:
 * - goods_receipt: Items received from suppliers/vendors (purchase orders)
 * - goods_issue: Items shipped to customers (order fulfillment)
 * - transfer: Items moved between warehouses
 * - adjustment_positive: Inventory count increases (stock corrections)
 * - adjustment_negative: Inventory count decreases (stock corrections)
 * - return_from_customer: Items returned by customers
 * - return_to_supplier: Items returned to suppliers/vendors
 */

import { query, queryOne } from './db';

export type TransactionType =
  | 'goods_receipt'
  | 'goods_issue'
  | 'transfer'
  | 'adjustment_positive'
  | 'adjustment_negative'
  | 'return_from_customer'
  | 'return_to_supplier';

export type ReferenceDocType = 'order' | 'purchase_order' | 'adjustment' | 'transfer';

export type PartnerType = 'supplier' | 'vendor';

export interface InventoryTransaction {
  id: string;
  transaction_number: string;
  transaction_type: TransactionType;
  transaction_date: Date;
  posting_date: Date;
  product_id: string;
  product_sku: string;
  product_name: string;
  quantity: number;
  unit_of_measure: string;
  warehouse_id?: string;
  warehouse_name?: string;
  storage_location?: string;
  from_warehouse_id?: string;
  from_warehouse_name?: string;
  to_warehouse_id?: string;
  to_warehouse_name?: string;
  supplier_id?: string;
  supplier_name?: string;
  partner_type?: PartnerType;
  reference_doc_type?: ReferenceDocType;
  reference_doc_id?: string;
  reference_doc_number?: string;
  unit_cost?: number;
  total_cost?: number;
  created_by_id?: string;
  created_by_username?: string;
  notes?: string;
  batch_number?: string;
  created_at: Date;
  updated_at: Date;
}

export interface LogTransactionParams {
  transaction_type: TransactionType;
  posting_date?: Date;
  product_id: string;
  product_sku: string;
  product_name: string;
  quantity: number; // Positive for receipts/increases, negative for issues/decreases
  unit_of_measure: string;
  warehouse_id?: string;
  warehouse_name?: string;
  storage_location?: string;
  from_warehouse_id?: string;
  from_warehouse_name?: string;
  to_warehouse_id?: string;
  to_warehouse_name?: string;
  supplier_id?: string;
  supplier_name?: string;
  partner_type?: PartnerType;
  reference_doc_type?: ReferenceDocType;
  reference_doc_id?: string;
  reference_doc_number?: string;
  unit_cost?: number;
  created_by_id?: string;
  created_by_username?: string;
  notes?: string;
  batch_number?: string;
}

/**
 * Logs an inventory transaction to the database
 * Transaction numbers are auto-generated by the database (MAT-YYYY-NNNNN)
 */
export async function logInventoryTransaction(
  params: LogTransactionParams
): Promise<InventoryTransaction> {
  const {
    transaction_type,
    posting_date = new Date(),
    product_id,
    product_sku,
    product_name,
    quantity,
    unit_of_measure,
    warehouse_id,
    warehouse_name,
    storage_location,
    from_warehouse_id,
    from_warehouse_name,
    to_warehouse_id,
    to_warehouse_name,
    supplier_id,
    supplier_name,
    partner_type,
    reference_doc_type,
    reference_doc_id,
    reference_doc_number,
    unit_cost,
    created_by_id,
    created_by_username,
    notes,
    batch_number,
  } = params;

  // Calculate total cost if unit cost is provided
  const total_cost = unit_cost ? Math.abs(quantity) * unit_cost : undefined;

  const transaction = await queryOne<InventoryTransaction>(
    `INSERT INTO inventory_transactions (
      transaction_type, posting_date,
      product_id, product_sku, product_name,
      quantity, unit_of_measure,
      warehouse_id, warehouse_name, storage_location,
      from_warehouse_id, from_warehouse_name,
      to_warehouse_id, to_warehouse_name,
      supplier_id, supplier_name, partner_type,
      reference_doc_type, reference_doc_id, reference_doc_number,
      unit_cost, total_cost,
      created_by_id, created_by_username,
      notes, batch_number
    ) VALUES (
      $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
      $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
      $21, $22, $23, $24, $25, $26
    ) RETURNING *`,
    [
      transaction_type,
      posting_date,
      product_id,
      product_sku,
      product_name,
      quantity,
      unit_of_measure,
      warehouse_id,
      warehouse_name,
      storage_location,
      from_warehouse_id,
      from_warehouse_name,
      to_warehouse_id,
      to_warehouse_name,
      supplier_id,
      supplier_name,
      partner_type,
      reference_doc_type,
      reference_doc_id,
      reference_doc_number,
      unit_cost,
      total_cost,
      created_by_id,
      created_by_username,
      notes,
      batch_number,
    ]
  );

  if (!transaction) {
    throw new Error('Failed to create inventory transaction');
  }

  return transaction;
}

/**
 * Logs a goods receipt (items received from supplier/vendor)
 */
export async function logGoodsReceipt(params: {
  product_id: string;
  product_sku: string;
  product_name: string;
  quantity: number;
  unit_of_measure: string;
  warehouse_id: string;
  warehouse_name: string;
  storage_location?: string;
  supplier_id: string;
  supplier_name: string;
  partner_type: PartnerType;
  purchase_order_id: string;
  purchase_order_number: string;
  unit_cost?: number;
  created_by_id?: string;
  created_by_username?: string;
  notes?: string;
  batch_number?: string;
}): Promise<InventoryTransaction> {
  return logInventoryTransaction({
    transaction_type: 'goods_receipt',
    product_id: params.product_id,
    product_sku: params.product_sku,
    product_name: params.product_name,
    quantity: Math.abs(params.quantity), // Ensure positive
    unit_of_measure: params.unit_of_measure,
    warehouse_id: params.warehouse_id,
    warehouse_name: params.warehouse_name,
    storage_location: params.storage_location,
    supplier_id: params.supplier_id,
    supplier_name: params.supplier_name,
    partner_type: params.partner_type,
    reference_doc_type: 'purchase_order',
    reference_doc_id: params.purchase_order_id,
    reference_doc_number: params.purchase_order_number,
    unit_cost: params.unit_cost,
    created_by_id: params.created_by_id,
    created_by_username: params.created_by_username,
    notes: params.notes,
    batch_number: params.batch_number,
  });
}

/**
 * Logs a goods issue (items shipped to customer)
 */
export async function logGoodsIssue(params: {
  product_id: string;
  product_sku: string;
  product_name: string;
  quantity: number;
  unit_of_measure: string;
  warehouse_id: string;
  warehouse_name: string;
  storage_location?: string;
  order_id: string;
  order_number: string;
  unit_cost?: number;
  created_by_id?: string;
  created_by_username?: string;
  notes?: string;
}): Promise<InventoryTransaction> {
  return logInventoryTransaction({
    transaction_type: 'goods_issue',
    product_id: params.product_id,
    product_sku: params.product_sku,
    product_name: params.product_name,
    quantity: -Math.abs(params.quantity), // Ensure negative
    unit_of_measure: params.unit_of_measure,
    warehouse_id: params.warehouse_id,
    warehouse_name: params.warehouse_name,
    storage_location: params.storage_location,
    reference_doc_type: 'order',
    reference_doc_id: params.order_id,
    reference_doc_number: params.order_number,
    unit_cost: params.unit_cost,
    created_by_id: params.created_by_id,
    created_by_username: params.created_by_username,
    notes: params.notes,
  });
}

/**
 * Logs a warehouse transfer (items moved between warehouses)
 */
export async function logWarehouseTransfer(params: {
  product_id: string;
  product_sku: string;
  product_name: string;
  quantity: number;
  unit_of_measure: string;
  from_warehouse_id: string;
  from_warehouse_name: string;
  to_warehouse_id: string;
  to_warehouse_name: string;
  unit_cost?: number;
  created_by_id?: string;
  created_by_username?: string;
  notes?: string;
}): Promise<InventoryTransaction> {
  return logInventoryTransaction({
    transaction_type: 'transfer',
    product_id: params.product_id,
    product_sku: params.product_sku,
    product_name: params.product_name,
    quantity: Math.abs(params.quantity),
    unit_of_measure: params.unit_of_measure,
    from_warehouse_id: params.from_warehouse_id,
    from_warehouse_name: params.from_warehouse_name,
    to_warehouse_id: params.to_warehouse_id,
    to_warehouse_name: params.to_warehouse_name,
    reference_doc_type: 'transfer',
    unit_cost: params.unit_cost,
    created_by_id: params.created_by_id,
    created_by_username: params.created_by_username,
    notes: params.notes,
  });
}

/**
 * Logs an inventory adjustment (stock correction)
 */
export async function logInventoryAdjustment(params: {
  product_id: string;
  product_sku: string;
  product_name: string;
  quantity: number; // Positive for increase, negative for decrease
  unit_of_measure: string;
  warehouse_id: string;
  warehouse_name: string;
  storage_location?: string;
  unit_cost?: number;
  created_by_id?: string;
  created_by_username?: string;
  notes?: string;
  reason: string;
}): Promise<InventoryTransaction> {
  const isPositive = params.quantity > 0;

  return logInventoryTransaction({
    transaction_type: isPositive ? 'adjustment_positive' : 'adjustment_negative',
    product_id: params.product_id,
    product_sku: params.product_sku,
    product_name: params.product_name,
    quantity: params.quantity,
    unit_of_measure: params.unit_of_measure,
    warehouse_id: params.warehouse_id,
    warehouse_name: params.warehouse_name,
    storage_location: params.storage_location,
    reference_doc_type: 'adjustment',
    unit_cost: params.unit_cost,
    created_by_id: params.created_by_id,
    created_by_username: params.created_by_username,
    notes: `${params.reason}${params.notes ? ` - ${params.notes}` : ''}`,
  });
}

/**
 * Logs a customer return (items returned by customer)
 */
export async function logCustomerReturn(params: {
  product_id: string;
  product_sku: string;
  product_name: string;
  quantity: number;
  unit_of_measure: string;
  warehouse_id: string;
  warehouse_name: string;
  storage_location?: string;
  order_id: string;
  order_number: string;
  unit_cost?: number;
  created_by_id?: string;
  created_by_username?: string;
  notes?: string;
}): Promise<InventoryTransaction> {
  return logInventoryTransaction({
    transaction_type: 'return_from_customer',
    product_id: params.product_id,
    product_sku: params.product_sku,
    product_name: params.product_name,
    quantity: Math.abs(params.quantity), // Ensure positive
    unit_of_measure: params.unit_of_measure,
    warehouse_id: params.warehouse_id,
    warehouse_name: params.warehouse_name,
    storage_location: params.storage_location,
    reference_doc_type: 'order',
    reference_doc_id: params.order_id,
    reference_doc_number: params.order_number,
    unit_cost: params.unit_cost,
    created_by_id: params.created_by_id,
    created_by_username: params.created_by_username,
    notes: params.notes,
  });
}

/**
 * Logs a return to supplier/vendor
 */
export async function logSupplierReturn(params: {
  product_id: string;
  product_sku: string;
  product_name: string;
  quantity: number;
  unit_of_measure: string;
  warehouse_id: string;
  warehouse_name: string;
  storage_location?: string;
  supplier_id: string;
  supplier_name: string;
  partner_type: PartnerType;
  purchase_order_id?: string;
  purchase_order_number?: string;
  unit_cost?: number;
  created_by_id?: string;
  created_by_username?: string;
  notes?: string;
}): Promise<InventoryTransaction> {
  return logInventoryTransaction({
    transaction_type: 'return_to_supplier',
    product_id: params.product_id,
    product_sku: params.product_sku,
    product_name: params.product_name,
    quantity: -Math.abs(params.quantity), // Ensure negative
    unit_of_measure: params.unit_of_measure,
    warehouse_id: params.warehouse_id,
    warehouse_name: params.warehouse_name,
    storage_location: params.storage_location,
    supplier_id: params.supplier_id,
    supplier_name: params.supplier_name,
    partner_type: params.partner_type,
    reference_doc_type: 'purchase_order',
    reference_doc_id: params.purchase_order_id,
    reference_doc_number: params.purchase_order_number,
    unit_cost: params.unit_cost,
    created_by_id: params.created_by_id,
    created_by_username: params.created_by_username,
    notes: params.notes,
  });
}

/**
 * Gets transaction history for a specific product
 */
export async function getProductTransactionHistory(
  productId: string,
  limit: number = 50
): Promise<InventoryTransaction[]> {
  return query<InventoryTransaction>(
    `SELECT * FROM inventory_transactions
     WHERE product_id = $1
     ORDER BY posting_date DESC, created_at DESC
     LIMIT $2`,
    [productId, limit]
  );
}

/**
 * Gets transaction history for a specific warehouse
 */
export async function getWarehouseTransactionHistory(
  warehouseId: string,
  limit: number = 50
): Promise<InventoryTransaction[]> {
  return query<InventoryTransaction>(
    `SELECT * FROM inventory_transactions
     WHERE warehouse_id = $1 
        OR from_warehouse_id = $1 
        OR to_warehouse_id = $1
     ORDER BY posting_date DESC, created_at DESC
     LIMIT $2`,
    [warehouseId, limit]
  );
}

/**
 * Gets recent transactions (for dashboard/overview)
 */
export async function getRecentTransactions(limit: number = 20): Promise<InventoryTransaction[]> {
  return query<InventoryTransaction>(
    `SELECT * FROM inventory_transactions
     ORDER BY created_at DESC
     LIMIT $1`,
    [limit]
  );
}
