import fs from 'fs';
import path from 'path';

/**
 * Get the ICC logo as a base64 data URI for embedding in PDFs
 * This ensures the logo appears in PDFs generated by PDFShift
 * without needing to fetch from an external URL
 */
export function getLogoDataURI(): string {
  try {
    const logoPath = path.join(process.cwd(), 'public', 'logo.png');
    const logoBuffer = fs.readFileSync(logoPath);
    const logoBase64 = logoBuffer.toString('base64');
    return `data:image/png;base64,${logoBase64}`;
  } catch (error) {
    console.error('Error reading logo file:', error);
    // Return empty string if logo can't be read
    return '';
  }
}
