import { cookies } from 'next/headers';
import { queryOne } from './db';
import { hashAdminPassword, verifyAdminPassword } from './admin-password';

// Supplier user interface
export interface SupplierUser {
  id: string;
  email: string;
  name: string;
  company_name: string;
  phone: string | null;
  supplier_number: string | null;
  is_active: boolean;
  tax_exempt: boolean;
  address_street: string | null;
  address_city: string | null;
  address_state: string | null;
  address_zip: string | null;
  created_at: string;
  updated_at: string;
}

// Supplier session interface
export interface SupplierSession {
  user: {
    id: string;
    email: string;
    name: string;
    company_name: string;
  };
  supplierUser: SupplierUser;
}

interface SupplierSessionRecord {
  id: string;
  supplier_user_id: string;
  token: string;
  expires_at: string;
}

interface SupplierUserWithPassword {
  id: string;
  email: string;
  name: string;
  company_name: string;
  phone: string | null;
  password_hash: string;
  is_active: boolean;
  failed_login_attempts: number | null;
  locked_until: string | null;
  created_at: string;
  updated_at: string;
}

// Get the current supplier session
export async function getSupplierSession(): Promise<SupplierSession | null> {
  const cookieStore = await cookies();
  const sessionToken = cookieStore.get('supplier_session')?.value;

  if (!sessionToken) {
    return null;
  }

  // Verify session token
  const sessionRecord = await queryOne<SupplierSessionRecord>(
    `SELECT * FROM supplier_sessions 
     WHERE token = $1 AND expires_at > NOW()`,
    [sessionToken]
  );

  if (!sessionRecord) {
    return null;
  }

  // Get supplier user details
  const supplierUser = await queryOne<SupplierUser>(
    `SELECT id, email, name, company_name, phone, is_active, tax_exempt, address_street, address_city, address_state, address_zip, created_at, updated_at
     FROM supplier_users
     WHERE id = $1 AND is_active = true`,
    [sessionRecord.supplier_user_id]
  );

  if (!supplierUser) {
    return null;
  }

  return {
    user: {
      id: supplierUser.id,
      email: supplierUser.email,
      name: supplierUser.name,
      company_name: supplierUser.company_name,
    },
    supplierUser,
  };
}

// Get supplier user by email
export async function getSupplierUserByEmail(email: string): Promise<SupplierUserWithPassword | null> {
  return queryOne<SupplierUserWithPassword>(
    `SELECT * FROM supplier_users WHERE email = $1`,
    [email]
  );
}

// Create supplier user
// Note: supplier_number is auto-generated by database trigger
export async function createSupplierUser(
  email: string,
  name: string,
  companyName: string,
  password: string,
  phone?: string,
  taxExempt: boolean = false,
  addressStreet?: string,
  addressCity?: string,
  addressState?: string,
  addressZip?: string
): Promise<SupplierUser> {
  const passwordHash = await hashAdminPassword(password);

  const result = await queryOne<SupplierUser>(
    `INSERT INTO supplier_users (email, name, company_name, password_hash, phone, tax_exempt, address_street, address_city, address_state, address_zip)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
     RETURNING id, email, name, company_name, phone, supplier_number, is_active, tax_exempt, address_street, address_city, address_state, address_zip, created_at, updated_at`,
    [email, name, companyName, passwordHash, phone || null, taxExempt, addressStreet || null, addressCity || null, addressState || null, addressZip || null]
  );

  if (!result) {
    throw new Error('Failed to create supplier user');
  }

  return result;
}

// Check if supplier email exists
export async function supplierEmailExists(email: string): Promise<boolean> {
  const result = await queryOne<{ id: string }>(
    'SELECT id FROM supplier_users WHERE email = $1',
    [email]
  );
  return !!result;
}

// Verify supplier password
export async function verifySupplierPassword(password: string, storedHash: string): Promise<boolean> {
  return verifyAdminPassword(password, storedHash);
}

// Lockout configuration (same as admin)
export const LOCKOUT_CONFIG = {
  maxAttempts: 5,
  lockoutDurationMinutes: 15,
};

