import { NextRequest, NextResponse } from 'next/server';
import { verifyAdminAuth } from '@/lib/admin-middleware';
import { query, queryOne } from '@/lib/db';
import { getClientIp } from '@/lib/rate-limit';
import { securityLogger } from '@/lib/security-logger';
import { z } from 'zod';

const vendorCreateSchema = z.object({
  name: z.string().min(1).max(255).trim(),
  address_id: z.number().int().positive().nullable().optional(),
  address1: z.string().max(255).trim().optional().nullable(),
  address2: z.string().max(255).trim().optional().nullable(),
  city: z.string().max(100).trim().optional().nullable(),
  state: z.string().max(2).trim().optional().nullable(),
  zip_code: z.string().max(20).trim().optional().nullable(),
  country: z.string().max(100).trim().optional().nullable(),
  tax_exempt: z.boolean().default(false),
  default_payment_terms: z.enum(['DUE_UPON_RECEIPT', 'NET_30', 'NET_60', 'NET_90', 'NET_180']).optional().nullable(),
  notes: z.string().max(5000).trim().optional().nullable(),
  is_active: z.boolean().default(true),
});

// const vendorUpdateSchema = vendorCreateSchema.partial(); // Unused - for future updates

// GET /api/admin/vendors - List all vendors
export async function GET(request: NextRequest) {
  const authResult = await verifyAdminAuth(request);
  if (!authResult.authorized) {
    return authResult.response!;
  }

  const ip = getClientIp(request);

  try {
    const vendors = await query<{
      id: number;
      vendor_number: string;
      name: string;
      address_id: number | null;
      tax_exempt: boolean;
      default_payment_terms: string | null;
      folder_path: string;
      is_active: boolean;
      notes: string | null;
      created_at: string;
      updated_at: string;
    }>(
      `SELECT id, vendor_number, name, address_id, tax_exempt, default_payment_terms, 
              folder_path, is_active, notes, created_at, updated_at
       FROM vendors
       ORDER BY name`
    );

    return NextResponse.json(vendors);
  } catch (error) {
    securityLogger.logError('Failed to fetch vendors', error, ip);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

// POST /api/admin/vendors - Create a new vendor
export async function POST(request: NextRequest) {
  const authResult = await verifyAdminAuth(request);
  if (!authResult.authorized) {
    return authResult.response!;
  }

  const ip = getClientIp(request);

  try {
    const body = await request.json();
    
    // Validate input
    const validationResult = vendorCreateSchema.safeParse(body);
    if (!validationResult.success) {
      securityLogger.logValidationFailure(
        '/api/admin/vendors',
        ip,
        validationResult.error.issues,
        'POST'
      );
      return NextResponse.json(
        { error: 'Validation failed', details: validationResult.error.issues },
        { status: 400 }
      );
    }

    const { name, address_id, address1, address2, city, state, zip_code, country, tax_exempt, default_payment_terms, notes, is_active } = validationResult.data;

    let finalAddressId = address_id || null;

    // If address fields are provided, create a new address
    if (address1 && city && state && zip_code) {
      const newAddress = await queryOne<{ id: number }>(
        `INSERT INTO addresses (type, company_name, address1, address2, city, state, zip_code, country)
         VALUES ('VENDOR', $1, $2, $3, $4, $5, $6, $7)
         RETURNING id`,
        [name, address1, address2 || null, city, state, zip_code, country || 'United States']
      );
      if (newAddress) {
        finalAddressId = newAddress.id;
      }
    }

    // Validate address_id if provided (and not created above)
    if (finalAddressId && !address1) {
      const address = await queryOne<{ id: number }>(
        'SELECT id FROM addresses WHERE id = $1',
        [finalAddressId]
      );
      if (!address) {
        return NextResponse.json(
          { error: 'Address not found' },
          { status: 400 }
        );
      }
    }

    // Insert vendor (vendor_number and folder_path are auto-generated by trigger)
    const vendor = await queryOne<{
      id: number;
      vendor_number: string;
      name: string;
      address_id: number | null;
      tax_exempt: boolean;
      default_payment_terms: string | null;
      folder_path: string;
      is_active: boolean;
      notes: string | null;
      created_at: string;
      updated_at: string;
    }>(
      `INSERT INTO vendors (name, address_id, tax_exempt, default_payment_terms, notes, is_active)
       VALUES ($1, $2, $3, $4, $5, $6)
       RETURNING id, vendor_number, name, address_id, tax_exempt, default_payment_terms, 
                 folder_path, is_active, notes, created_at, updated_at`,
      [name, finalAddressId, tax_exempt, default_payment_terms || null, notes || null, is_active ?? true]
    );

    if (!vendor) {
      return NextResponse.json(
        { error: 'Failed to create vendor' },
        { status: 500 }
      );
    }

    securityLogger.logEvent({
      type: 'admin_action',
      ip,
      path: '/api/admin/vendors',
      method: 'POST',
      details: {
        action: 'vendor_created',
        vendor_id: vendor.id,
        vendor_number: vendor.vendor_number,
        vendor_name: vendor.name,
      },
      severity: 'low',
    });

    return NextResponse.json(vendor, { status: 201 });
  } catch (error) {
    securityLogger.logError('Failed to create vendor', error, ip);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

