/**
 * Test BOL Email Sending Logic
 * 
 * This script tests the complete email sending flow for BOL and SDS documents:
 * 1. Validates all required configurations
 * 2. Tests Resend API connectivity
 * 3. Tests PDF generation (PDFShift)
 * 4. Tests S3 document fetching
 * 5. Sends a test email with a PDF attachment
 * 
 * Run with: dotenv -e .env.local -- pnpm tsx scripts/test-bol-email-send.ts <test-email>
 * Example: dotenv -e .env.local -- pnpm tsx scripts/test-bol-email-send.ts your-email@example.com
 * 
 * Or set environment variables manually:
 * RESEND_API_KEY=re_... PDFSHIFT_API_KEY=... EMAIL_FROM=... pnpm tsx scripts/test-bol-email-send.ts your-email@example.com
 */

import { generatePDFWithPDFShift } from '@/lib/pdf-generation';
import { Resend } from 'resend';

async function testBOLEmailSending() {
  const testEmail = process.argv[2];
  
  if (!testEmail) {
    console.error('❌ Please provide a test email address');
    console.log('Usage: pnpm tsx scripts/test-bol-email-send.ts <test-email>');
    process.exit(1);
  }

  console.log('🧪 Testing BOL Email Sending Logic\n');
  console.log('=====================================\n');

  // Test 1: Check Resend API Connectivity
  console.log('Test 1: Resend API Connectivity');
  console.log('--------------------------------');
  try {
    console.log('   Testing connection to api.resend.com...');
    const connectivityTest = await fetch('https://api.resend.com', {
      method: 'HEAD',
      signal: AbortSignal.timeout(5000),
    });
    console.log(`   ✅ Resend API is reachable (Status: ${connectivityTest.status})`);
  } catch (error) {
    console.error('   ❌ Cannot reach Resend API:', error instanceof Error ? error.message : String(error));
    console.error('   ⚠️  This will cause email sending to fail');
    console.error('   Check: 1) Internet connection, 2) DNS resolution, 3) Firewall settings');
  }
  console.log('');

  // Test 2: Validate Resend Configuration
  console.log('Test 2: Resend Email Configuration');
  console.log('-----------------------------------');
  const resendKey = process.env.RESEND_API_KEY;
  const emailFrom = process.env.EMAIL_FROM;

  if (!resendKey) {
    console.error('❌ RESEND_API_KEY is not set');
    process.exit(1);
  }
  
  if (!resendKey.startsWith('re_')) {
    console.error('❌ RESEND_API_KEY appears invalid (should start with "re_")');
    process.exit(1);
  }
  
  console.log(`✅ RESEND_API_KEY is set (${resendKey.substring(0, 7)}...${resendKey.substring(resendKey.length - 4)})`);

  if (!emailFrom) {
    console.error('❌ EMAIL_FROM is not set');
    process.exit(1);
  }
  
  console.log(`✅ EMAIL_FROM is set: ${emailFrom}`);
  console.log('');

  // Test 3: Test PDF Generation (PDFShift)
  console.log('Test 3: PDF Generation (PDFShift)');
  console.log('-----------------------------------');
  const pdfshiftKey = process.env.PDFSHIFT_API_KEY;
  
  if (!pdfshiftKey) {
    console.error('❌ PDFSHIFT_API_KEY is not set');
    console.error('   BOL PDFs cannot be generated without PDFShift');
    process.exit(1);
  }
  
  console.log(`✅ PDFSHIFT_API_KEY is set (${pdfshiftKey.substring(0, 7)}...${pdfshiftKey.substring(pdfshiftKey.length - 4)})`);
  
  // Generate a test PDF
  const testHTML = `
<!DOCTYPE html>
<html>
<head>
  <title>Test BOL</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; }
    h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
    .info { background: #f0fdf4; border-left: 4px solid #22c55e; padding: 15px; margin: 20px 0; }
  </style>
</head>
<body>
  <h1>Test Bill of Lading</h1>
  <div class="info">
    <p><strong>Order Number:</strong> TEST-001</p>
    <p><strong>Generated:</strong> ${new Date().toISOString()}</p>
    <p><strong>Status:</strong> Test PDF for email sending validation</p>
  </div>
  <p>This is a test PDF generated by PDFShift to verify email attachment functionality.</p>
</body>
</html>
  `;
  
  try {
    console.log('   Generating test PDF with PDFShift...');
    const pdfBuffer = await generatePDFWithPDFShift(testHTML);
    console.log(`   ✅ PDF generated successfully (${pdfBuffer.length} bytes / ${(pdfBuffer.length / 1024).toFixed(2)} KB)`);
    
    // Validate PDF
    const pdfHeader = pdfBuffer.toString('ascii', 0, 4);
    if (pdfHeader === '%PDF') {
      console.log('   ✅ PDF is valid (starts with %PDF)');
    } else {
      console.error(`   ❌ PDF is invalid (header: ${pdfHeader})`);
      process.exit(1);
    }
  } catch (error) {
    console.error('   ❌ PDF generation failed:', error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
  console.log('');

  // Test 4: Validate S3 Configuration (for SDS documents)
  console.log('Test 4: S3 Configuration (for SDS documents)');
  console.log('----------------------------------------------');
  const awsAccessKey = process.env.AWS_ACCESS_KEY_ID;
  const awsSecretKey = process.env.AWS_SECRET_ACCESS_KEY;
  const awsBucket = process.env.AWS_S3_BUCKET_NAME;
  const awsRegion = process.env.AWS_REGION;

  if (!awsAccessKey || !awsSecretKey || !awsBucket || !awsRegion) {
    console.warn('⚠️  AWS credentials not fully configured');
    console.warn('   SDS documents cannot be fetched from S3 without AWS credentials');
    console.warn('   Email sending will still work, but SDS attachments will fail');
  } else {
    console.log('✅ AWS credentials are configured');
    console.log(`   Bucket: ${awsBucket}`);
    console.log(`   Region: ${awsRegion}`);
  }
  console.log('');

  // Test 5: Send Test Email with PDF Attachment
  console.log('Test 5: Send Test Email with PDF Attachment');
  console.log('--------------------------------------------');
  console.log(`   From: ${emailFrom}`);
  console.log(`   To: ${testEmail}`);
  console.log(`   Subject: Test BOL Email - ${new Date().toISOString()}`);
  console.log('   Attachment: Test BOL PDF');
  console.log('');

  try {
    const resend = new Resend(resendKey);
    
    // Generate PDF for attachment
    const pdfBuffer = await generatePDFWithPDFShift(testHTML);
    
    // Send email with PDF attachment
    console.log('   Sending email with PDF attachment...');
    const result = await resend.emails.send({
      from: emailFrom,
      to: testEmail,
      subject: `Test BOL Email - ${new Date().toISOString()}`,
      html: `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Test BOL Email</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
  <div style="background-color: #f8f9fa; border-radius: 8px; padding: 30px; margin-bottom: 20px;">
    <h1 style="color: #2563eb; margin: 0 0 10px 0;">✅ BOL Email Test Successful</h1>
    <p style="margin: 0;">This is a test email to verify BOL email sending functionality.</p>
  </div>

  <div style="margin-bottom: 20px;">
    <h2 style="color: #2563eb; font-size: 18px;">Test Details</h2>
    <p><strong>Sent at:</strong> ${new Date().toLocaleString()}</p>
    <p><strong>PDF Attachment:</strong> Test BOL PDF (${(pdfBuffer.length / 1024).toFixed(2)} KB)</p>
    <p><strong>Status:</strong> All systems operational</p>
  </div>

  <div style="background-color: #dcfce7; padding: 15px; border-radius: 6px; border-left: 4px solid #22c55e;">
    <p style="margin: 0;"><strong>Success!</strong> Your BOL email system is working correctly.</p>
    <p style="margin: 10px 0 0 0;">You can now send BOL emails with PDF attachments to carriers.</p>
  </div>

  <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; color: #666; font-size: 12px;">
    <p><strong>Next Steps:</strong></p>
    <ul>
      <li>Test sending BOL emails from the admin panel</li>
      <li>Verify SDS documents can be attached</li>
      <li>Check carrier email delivery</li>
    </ul>
  </div>
</body>
</html>
      `,
      attachments: [
        {
          filename: `test-bol-${Date.now()}.pdf`,
          content: pdfBuffer.toString('base64'),
        },
      ],
    });

    if (result.error) {
      console.error('   ❌ Email sending failed:');
      console.error(`      Error: ${result.error.message || JSON.stringify(result.error)}`);
      process.exit(1);
    }

    console.log(`   ✅ Email sent successfully!`);
    console.log(`   Message ID: ${result.data?.id || 'N/A'}`);
    console.log('');
    console.log('✅ All tests passed!');
    console.log('');
    console.log('📧 Check your inbox at:', testEmail);
    console.log('   You should receive an email with a PDF attachment.');
    console.log('');
    console.log('🎉 Your BOL email system is ready to use!');
    console.log('');
    console.log('Next steps:');
    console.log('1. Go to the admin panel');
    console.log('2. Open an order');
    console.log('3. Click "Send BOL Email"');
    console.log('4. Select BOL and/or SDS documents');
    console.log('5. Enter carrier email address');
    console.log('6. Send the email');
    
  } catch (error) {
    console.error('   ❌ Email sending failed:');
    console.error(`      Error: ${error instanceof Error ? error.message : String(error)}`);
    
    if (error instanceof Error) {
      const errorMsg = error.message.toLowerCase();
      if (errorMsg.includes('domain') || errorMsg.includes('verify')) {
        console.error('');
        console.error('   💡 Suggestion: Verify your sender domain in Resend dashboard');
        console.error('      Visit: https://resend.com/domains');
      } else if (errorMsg.includes('api key') || errorMsg.includes('unauthorized')) {
        console.error('');
        console.error('   💡 Suggestion: Check your RESEND_API_KEY');
        console.error('      Visit: https://resend.com/api-keys');
      } else if (errorMsg.includes('unable to fetch') || errorMsg.includes('network')) {
        console.error('');
        console.error('   💡 Suggestion: Network connectivity issue');
        console.error('      Check: 1) Internet connection, 2) DNS resolution, 3) Firewall');
      }
    }
    
    process.exit(1);
  }
}

testBOLEmailSending().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});

